### ISSUE TITLE
First commit isseus

### ISSUE THREAD

**Issue by rtrivedi39** [rtrivedi39/alzeria#1]
1. Menu change "menebers" to "Users"
2. Only "property_design" page have breadcrumb rest ????
3. "master/property_design_create" change label names -> "Property Name" to Design type name 
4. All master create form and table labels are same.
5. "setting menu" On update remove required to logo and favicon image.
6. time zone must be selected by default.
7. All masters doesn't have similar columns and status color label. Use -> shoe_status() function.
8. Add edit members breadcrumb missing.
9. Add Role part missing.
10. Add drop down list of "Report to User " and "User Role" drop down and "User Status" must be single selective.
11. "User Status Message" mandatory if status inactive , not all time req.
12. Password filed panel must be diff not on update page.

**Comment by akashbadone** [comment]
1,2,3,4,5,8 errors solved ,
working on others...

**Comment by akashbadone** [comment]
9,10,11,12 errors solved

**Comment by rtrivedi39** [comment]
Completed
